question_data = [
    {
        "category": "Entertainment: Video Games",
        "type": "boolean", "difficulty": "easy",
        "question": "In &quot;Super Mario 64&quot;, collecting 100 coins on a level will give you a 1-UP.",
        "correct_answer": "False",
        "incorrect_answers": ["True"]
    }, {"category": "Entertainment: Books", "type": "boolean", "difficulty": "easy", "question": "The book 1984 was published in 1949.", "correct_answer": "True", "incorrect_answers": ["False"]}, {"category": "Science: Computers", "type": "boolean", "difficulty": "medium", "question": "To bypass US Munitions Export Laws, the creator of the PGP published all the source code in book form. ", "correct_answer": "True", "incorrect_answers": ["False"]}, {"category": "Politics", "type": "boolean", "difficulty": "easy", "question": "The 2016 United States Presidential Election is the first time Hillary Clinton has run for President.", "correct_answer": "False", "incorrect_answers": ["True"]}, {"category": "Science: Computers", "type": "boolean", "difficulty": "easy", "question": "&quot;HTML&quot; stands for Hypertext Markup Language.", "correct_answer": "True", "incorrect_answers": ["False"]}, {
        "category": "Politics", "type": "boolean", "difficulty": "medium", "question": "During the 2016 United States presidential election, the State of California possessed the most electoral votes, having 55.", "correct_answer": "True", "incorrect_answers": ["False"]}, {"category": "Science & Nature", "type": "boolean", "difficulty": "hard", "question": "The chemical element Lithium is named after the country of Lithuania.", "correct_answer": "False", "incorrect_answers": ["True"]}, {"category": "Entertainment: Music", "type": "boolean", "difficulty": "medium", "question": "Nick Mason is the only member to appear on every Pink Floyd album.", "correct_answer": "True", "incorrect_answers": ["False"]}, {"category": "General Knowledge", "type": "boolean", "difficulty": "medium", "question": "Francis Bacon died from a fatal case of pneumonia while he was attempting to preserve meat by stuffing a chicken with snow.", "correct_answer": "True", "incorrect_answers": ["False"]}, {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy", "question": "The game &quot;Jetpack Joyride&quot; was created by &quot;Redbrick Studios&quot;.", "correct_answer": "False", "incorrect_answers": ["True"]}]
